//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WSSemanticSearch.srvExpansionConsulta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExpancionConsultaSoap", Namespace="http://tempuri.org/")]
    public partial class ExpancionConsulta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExpandirConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CargarConceptosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetornarConceptosOntologiaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExpancionConsulta() {
            this.Url = global::WSSemanticSearch.Properties.Settings.Default.WSSemanticSearch_srvExpansionConsulta_ExpancionConsulta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExpandirConsultaCompletedEventHandler ExpandirConsultaCompleted;
        
        /// <remarks/>
        public event CargarConceptosCompletedEventHandler CargarConceptosCompleted;
        
        /// <remarks/>
        public event RetornarConceptosOntologiaCompletedEventHandler RetornarConceptosOntologiaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExpandirConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ExpandirConsulta(string CaminoOntologia, string consulta, string tipoAnalizador) {
            object[] results = this.Invoke("ExpandirConsulta", new object[] {
                        CaminoOntologia,
                        consulta,
                        tipoAnalizador});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ExpandirConsultaAsync(string CaminoOntologia, string consulta, string tipoAnalizador) {
            this.ExpandirConsultaAsync(CaminoOntologia, consulta, tipoAnalizador, null);
        }
        
        /// <remarks/>
        public void ExpandirConsultaAsync(string CaminoOntologia, string consulta, string tipoAnalizador, object userState) {
            if ((this.ExpandirConsultaOperationCompleted == null)) {
                this.ExpandirConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExpandirConsultaOperationCompleted);
            }
            this.InvokeAsync("ExpandirConsulta", new object[] {
                        CaminoOntologia,
                        consulta,
                        tipoAnalizador}, this.ExpandirConsultaOperationCompleted, userState);
        }
        
        private void OnExpandirConsultaOperationCompleted(object arg) {
            if ((this.ExpandirConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExpandirConsultaCompleted(this, new ExpandirConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarConceptos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CargarConceptos(string CaminoOntologia) {
            object[] results = this.Invoke("CargarConceptos", new object[] {
                        CaminoOntologia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CargarConceptosAsync(string CaminoOntologia) {
            this.CargarConceptosAsync(CaminoOntologia, null);
        }
        
        /// <remarks/>
        public void CargarConceptosAsync(string CaminoOntologia, object userState) {
            if ((this.CargarConceptosOperationCompleted == null)) {
                this.CargarConceptosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarConceptosOperationCompleted);
            }
            this.InvokeAsync("CargarConceptos", new object[] {
                        CaminoOntologia}, this.CargarConceptosOperationCompleted, userState);
        }
        
        private void OnCargarConceptosOperationCompleted(object arg) {
            if ((this.CargarConceptosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarConceptosCompleted(this, new CargarConceptosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetornarConceptosOntologia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetornarConceptosOntologia(string CaminoOntologia, string consulta, string tipoAnalizador) {
            object[] results = this.Invoke("RetornarConceptosOntologia", new object[] {
                        CaminoOntologia,
                        consulta,
                        tipoAnalizador});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RetornarConceptosOntologiaAsync(string CaminoOntologia, string consulta, string tipoAnalizador) {
            this.RetornarConceptosOntologiaAsync(CaminoOntologia, consulta, tipoAnalizador, null);
        }
        
        /// <remarks/>
        public void RetornarConceptosOntologiaAsync(string CaminoOntologia, string consulta, string tipoAnalizador, object userState) {
            if ((this.RetornarConceptosOntologiaOperationCompleted == null)) {
                this.RetornarConceptosOntologiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornarConceptosOntologiaOperationCompleted);
            }
            this.InvokeAsync("RetornarConceptosOntologia", new object[] {
                        CaminoOntologia,
                        consulta,
                        tipoAnalizador}, this.RetornarConceptosOntologiaOperationCompleted, userState);
        }
        
        private void OnRetornarConceptosOntologiaOperationCompleted(object arg) {
            if ((this.RetornarConceptosOntologiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornarConceptosOntologiaCompleted(this, new RetornarConceptosOntologiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ExpandirConsultaCompletedEventHandler(object sender, ExpandirConsultaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExpandirConsultaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExpandirConsultaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CargarConceptosCompletedEventHandler(object sender, CargarConceptosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarConceptosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarConceptosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RetornarConceptosOntologiaCompletedEventHandler(object sender, RetornarConceptosOntologiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornarConceptosOntologiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetornarConceptosOntologiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591